/Users/jinseopsong/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "/Users/jinseopsong/coding/LD50-Prediction/src/run.py", line 92, in <module>
    t.train()
  File "/Users/jinseopsong/coding/LD50-Prediction/src/run.py", line 64, in train
    loss.backward()
  File "/Users/jinseopsong/Library/Python/3.9/lib/python/site-packages/torch/_tensor.py", line 525, in backward
    torch.autograd.backward(
  File "/Users/jinseopsong/Library/Python/3.9/lib/python/site-packages/torch/autograd/__init__.py", line 267, in backward
    _engine_run_backward(
  File "/Users/jinseopsong/Library/Python/3.9/lib/python/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Found dtype Long but expected Float