Traceback (most recent call last):
  File "/Users/jinseopsong/coding/LD50-Prediction/src/run.py", line 92, in <module>
    t.train()
  File "/Users/jinseopsong/coding/LD50-Prediction/src/run.py", line 63, in train
    loss = self.loss(out, y)
  File "/Users/jinseopsong/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/jinseopsong/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/jinseopsong/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/loss.py", line 1185, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/Users/jinseopsong/Library/Python/3.9/lib/python/site-packages/torch/nn/functional.py", line 3086, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
IndexError: Target -1 is out of bounds.